apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts
  labels:
    app: cts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts
  template:
    metadata:
      labels:
        app: cts
    spec:
      containers:
      - name: cts-pod
        image: msp-registry.sidhcmsp.nutanix.com:5001/cts
#        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-root-username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: cts
  labels:
    app: cts
  annotations:
    service.msp.ntnx.io/lb: pc-internal
spec:
  selector:
    app: cts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1235
      targetPort: 8080
      # nodePort: 30001
